// angular-example/src/app/app.component.ts
import { Component, Inject, Self } from '@angular/core'
import { root } from 'rxjs/internal-compatibility'
import { RootStateService } from '../reducers/app.reducer.service'
import { changeAge, changeName, rootReducer, save } from '../reducers/RootReducer'
import { IRootState } from '../reducers/RootState'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-example'
  state: IRootState = rootReducer.getState()
  constructor(public rootStateService: RootStateService) {
    rootReducer.subscribe((state) => {
      this.state = state
    })
  }
  _handleOnChangeName(e: Event) {
    const target = e.target as HTMLInputElement
    rootReducer.dispatch(changeName(target.value))
  }
  _handleOnChangeAge(e: Event) {
    const target = e.target as HTMLInputElement
    rootReducer.dispatch(changeAge(parseInt(target.value, 10)))
  }
  _handleOnSave(e: Event) {
    e.preventDefault()
    rootReducer.dispatch(save())
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  .app {
    text-align: center;
  }
</style>
<div class="app">
  <div>
    <img
      width="200"
      alt="Angular Logo"
      src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
    />
  </div>
  <form (submit)="_handleOnSave($event)">
    <p>Name: <input type="text" [disabled]="state.saving" [value]="state.name" (input)="_handleOnChangeName($event)" /></p>
    <p>Age: <input type="number" [disabled]="state.saving" [value]="state.age" (input)="_handleOnChangeAge($event)" /></p>
    <button type="submit" [disabled]="state.saving">
      {{state.saving ? 'saving...' : 'save'}}
    </button>
  </form>
</div>

// react-example/src/App.tsx
import React, { ChangeEvent, FormEvent, useCallback } from 'react'
import logo from './logo.svg'
import './App.css';
import { changeAge, changeName, rootReducer, save } from './reducers/RootReducer'

function App() {
  const [state, dispatch] = rootReducer.useFluentReducer()
  const _handleOnChangeName = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    dispatch(changeName(e.target.value))
  }, [dispatch])
  const _handleOnChangeAge = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    dispatch(changeAge(parseInt(e.target.value, 10)))
  }, [dispatch])
  const _handleOnSubmit = useCallback((e: FormEvent) => {
    e.preventDefault()
    dispatch(save())
  }, [dispatch])
  return (
    <form className="App" onSubmit={_handleOnSubmit}>
      <div>
        <img src={logo} className="App-logo" alt="logo" />
      </div>
      <p>Name: <input type="text" value={state.name} disabled={state.saving} onChange={_handleOnChangeName}/></p>
      <p>Age: <input type="number" value={state.age} disabled={state.saving} onChange={_handleOnChangeAge}/></p>
      <button type="submit" disabled={state.saving}>
        {state.saving ? 'saving...' : 'save'}
      </button>
    </form>
  )
}

export default App;
